# Generated by Django 2.2.10 on 2020-06-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
